pipeline {
    agent any

    environment {
        GIT_URL = "https://github.com/homubee/Jwebcrawler.git"
    }

    stages {
        stage('Pull') {
            steps {
                git url: "${GIT_URL}", branch: "main"
            }
        }
        
        stage('Clean') {
            steps {
                sh '(docker stop jwebcralwer && docker rm jwebcralwer) || true'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t jwebcralwer ./backend'
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'docker run -it -d -p 8090:8090 --name jwebcralwer jwebcralwer'
            }
        }
    }
}