pipeline {
    agent any

    environment {
        GIT_URL = "https://github.com/homubee/Jwebcrawler.git"
    }

    stages {
        stage('Pull') {
            steps {
                git url: "${GIT_URL}", branch: "main"
            }
        }

        stage('Build and Deploy') {
            steps {
                sh 'sudo docker compose stop'
                sh 'sudo docker compose up -d --build'
            }
        }
    }
}